### ISSUE TITLE
P2Pool status doesn't get green even if synced if log verbosity is under level 3

### ISSUE THREAD

**Issue by MKRajan29** [Cyrix126/gupaxx#18] opened 2024-10-08 08:33 UTC
## OS & Version:
e.g: Windows 11, Gupaxx v1.5.0

## Bug
The status light of P2Pool and XvB is Orange and even though it is finding shares (i think the share was already before updating, but I never know. It is well after PPLNS window since the update). Also the P2Pool subTab in status Tab is not displaying the P2Pool Status. All this has started in the new 1.5.0. A tutorial for 1.5.0 is needed.

## Steps
1. Set up Gupaxx..
3. Setup Node, (node database size is also not updating). Node directory is at a custom location
4. Setup P2Pool and start it. The Orange status light at the bottom is still not green, been running for 15 hours now (even though i got a payout from the share a few moments back)
5. Run Xmrig and Run XvB
6. Now following the P2Pool tab, the XvB status is also orange and the hash is being sent or not is not clear. (XmRig and Node are green).

## Screenshots
![image](https://github.com/user-attachments/assets/ca8a50bf-68d0-43df-83b4-eadeb2edb280)
![image](https://github.com/user-attachments/assets/37142360-5937-4b2a-95a8-32542bb92ddd)
![image](https://github.com/user-attachments/assets/0c22b0bf-aaa3-489b-bc8b-cbc08817452e)

## Crash report
No crashing

##Additional comments
Also the status tab never displays all the headings in a single glance. Couldn't ever figure out how Width/Height Adjust works.

**Comment by Cyrix126** [comment] 2024-10-08 14:00
Hello, thanks for the bug report.

The XvB status is orange and the sub menu p2pool of status Tab is not active since p2pool status is orange.

>  the hash is being sent or not is not clear.

If the XvB status is orange, HR will never be sent on XvB, all will be sent to p2pool.

Apparently the p2pool console output is not displaying the lines detected by Gupaxx to tell if it's done synchronizing. 
I'll try to reproduce in a VM, do you use simple or advanced mode in p2pool tab ? if advanced, with which options ?.

> (node database size is also not updating)

Does it update when using the same storage as monerod ? 
Again, I'll try to reproduce.

> Also the status tab never displays all the headings in a single glance. Couldn't ever figure out how Width/Height Adjust works.

It can not currently since the size of the text is dependent of the size of the window. It's a design decision from upstream that I plan to change. There is a horizontal scrollbar in the mean time.

**Comment by MKRajan29** [comment] 2024-10-08 14:25
>  HR will never be sent on XvB, all will be sent to p2pool.

If that's the case then in the status why is the XvB output lit even though the strobe is orange for XvB

> I'll try to reproduce in a VM, do you use simple or advanced mode in p2pool tab ? if advanced, with which options ?.

![image](https://github.com/user-attachments/assets/b1eaf905-11ee-4928-931f-6c5443963f51)

This was working fine with the last update and nothing did i change after the updating. It was acting weird when i just updated it, but then i went ahead and started with the 1.5.0 bundle from scratch.

![image](https://github.com/user-attachments/assets/26835551-df30-4b53-9614-fbdfca614cf9)

> Does it update when using the same storage as monerod ?

I have only one drive. Also the binary and database for the blockchain are in the same directory under subfolders. This is the same database that the GUI Wallet was using. Now that after the introduction of the Node in this update, I have not run the GUI Wallet anymore.

> There is a horizontal scrollbar in the mean time.

Yes, but that's weird scrolling into it.

Also is this normal?

![image](https://github.com/user-attachments/assets/ef24fb13-e797-4930-98ba-5bb317cea460)

Also when cycling through the Processes, P2Pool and Benchmarks activates the save and reset button even though there is nothing edited or changed there and neither possible.

![image](https://github.com/user-attachments/assets/71fbf74e-4e5f-4460-9409-eb6b3a256d17)

**Comment by Cyrix126** [comment] 2024-10-08 15:00
> If that's the case then in the status why is the XvB output lit even though the strobe is orange for XvB

It list public data from XvB since it can (it only needs an internet connection to work). So even if the algorithm can't be enabled because p2pool is not ready, you can still see the stats. It is written in the XvB console: 
`XvB process is started only to get public stats.`

> Also when cycling through the Processes, P2Pool and Benchmarks activates the save and reset button even though there is nothing edited or changed there and neither possible.

It is to remember the last submenu you were to open it first next time you start Gupaxx and go to Status Tab.

I can reproduce the bug of the 0B size on Windows, not on Linux. Will investigate further when the p2pool issue will be understood and fixed.

For the Warnings:
About the port it's not an issue, it just help the network more if it's open. 
About the txt dns it's because you'r using a DNS (likely the one of your ISP) that do not support dnssec, which is needed to resolve Moneropulse. Again not a big issue.

Theses Warnings should not be the cause of the issue of p2pool not getting green.

Can you post the output of the p2pool console when it is finishing synchronizing ? Gupaxx will set p2pool to green if a line contains "depth = 0" which should happen every time p2pool adds a block after synchronizing.

**Comment by MKRajan29** [comment] 2024-10-08 16:34
NOTICE  2024-10-08 16:24:09.1391 Log started
NOTICE  2024-10-08 16:24:09.1400 P2Pool v4.1.1 (built with MSVC/1941 on Sep 30 2024)
NOTICE  2024-10-08 16:24:09.1400 Util UPnP: Started scanning for UPnP IGD devices
NOTICE  2024-10-08 16:24:09.1403 SideChain network type  = mainnet
NOTICE  2024-10-08 16:24:09.1403 SideChain using default config
NOTICE  2024-10-08 16:24:09.1403 SideChain pool name     = mini
NOTICE  2024-10-08 16:24:09.1403 SideChain block time    = 10 seconds
NOTICE  2024-10-08 16:24:09.1403 SideChain min diff      = 100000
NOTICE  2024-10-08 16:24:09.1403 SideChain PPLNS window  = 2160 blocks
NOTICE  2024-10-08 16:24:09.1403 SideChain uncle penalty = 20%
NOTICE  2024-10-08 16:24:09.1403 SideChain generating consensus ID
NOTICE  2024-10-08 16:24:09.1403 SideChain consensus ID = xxx
NOTICE  2024-10-08 16:24:09.1413 RandomX_Hasher allocated 512 MB
NOTICE  2024-10-08 16:24:09.1419 TCPServer listening on 127.0.0.1:61766
NOTICE  2024-10-08 16:24:09.1419 ConsoleCommands event loop started
NOTICE  2024-10-08 16:24:09.1498 RandomX_Hasher new seed xxxx
NOTICE  2024-10-08 16:24:09.1501 P2Pool 127.0.0.1:18081:ZMQ:18083 ping is 0.101 ms
NOTICE  2024-10-08 16:24:09.1509 RandomX_Hasher old seed xxxx
NOTICE  2024-10-08 16:24:09.4280 RandomX_Hasher cache updated
NOTICE  2024-10-08 16:24:09.7199 RandomX_Hasher old cache updated
NOTICE  2024-10-08 16:24:09.7238 TCPServer listening on [::]:3333
NOTICE  2024-10-08 16:24:09.7242 TCPServer listening on 0.0.0.0:3333
NOTICE  2024-10-08 16:24:09.7243 StratumServer event loop started
NOTICE  2024-10-08 16:24:09.7247 BlockCache loading cached blocks
NOTICE  2024-10-08 16:24:10.7718 BlockCache loaded 4608 cached blocks
NOTICE  2024-10-08 16:24:11.7021 TCPServer listening on [::]:37888
NOTICE  2024-10-08 16:24:11.7026 TCPServer listening on 0.0.0.0:37888
NOTICE  2024-10-08 16:24:11.7026 Util UPnP: trying to map WAN:37888 to LAN:37888
NOTICE  2024-10-08 16:24:13.1862 Util UPnP: Finished scanning for UPnP IGD devices
WARNING 2024-10-08 16:24:13.1862 Util upnpDiscover: no UPnP IGD devices found, error 0
NOTICE  2024-10-08 16:24:13.1864 P2PServer event loop started
NOTICE  2024-10-08 16:24:13.1972 ZMQReader connected to tcp://127.0.0.1:58235
NOTICE  2024-10-08 16:24:13.1990 ZMQReader connected to tcp://127.0.0.1:18083
NOTICE  2024-10-08 16:24:13.1992 ZMQReader worker thread ready
NOTICE  2024-10-08 16:24:13.1993 ZMQReader monitor thread ready
NOTICE  2024-10-08 16:24:13.2063 P2Pool 127.0.0.1:18081:ZMQ:18083 ping is 0.333 ms
NOTICE  2024-10-08 16:24:20.4760 SideChain SYNCHRONIZED
NOTICE  2024-10-08 16:24:20.4763 StratumServer SHARE FOUND: mainchain height 3254666, sidechain height 0, diff 100000, client 127.0.0.1:59246, user XXX, effort 100.001%
NOTICE  2024-10-08 16:24:24.8433 StratumServer SHARE FOUND: mainchain height 3254666, sidechain height 1, diff 100000, client 127.0.0.1:59246, user XXX, effort 200.002%
NOTICE  2024-10-08 16:24:30.4679 StratumServer SHARE FOUND: mainchain height 3254666, sidechain height 2, diff 100000, client 127.0.0.1:59246, user XXX, effort 100.001%
NOTICE  2024-10-08 16:24:40.6797 StratumServer SHARE FOUND: mainchain height 3254666, sidechain height 3, diff 133333, client 127.0.0.1:59246, user XXX, effort 75.001%
NOTICE  2024-10-08 16:24:57.6629 SideChain add_external_block: block fb433e34b56847e17d33bbed09c1bfa644611de0da0500f1379121bee1a0fea2 has enough PoW for Monero height 3254500, submitting it
NOTICE  2024-10-08 16:24:57.6630 P2Pool submit_block: height = 3254666, external blob (24218 bytes)
NOTICE  2024-10-08 16:25:07.8968 StratumServer SHARE FOUND: mainchain height 3254666, sidechain height 4, diff 158730, client 127.0.0.1:59246, user XXX, effort 126.001%
NOTICE  2024-10-08 16:25:15.1135 StratumServer SHARE FOUND: mainchain height 3254666, sidechain height 5, diff 158730, client 127.0.0.1:59246, user XXX, effort 63.001%
NOTICE  2024-10-08 16:25:34.4330 SideChain add_external_block: block 45d4bdf289c1062ca75d771235f1af43e9d5f647a7f1f1eae438aa7d85813c85 has enough PoW for Monero height 3254354, submitting it
NOTICE  2024-10-08 16:25:34.4330 P2Pool submit_block: height = 3254668, external blob (24411 bytes)
NOTICE  2024-10-08 16:25:51.0003 SideChain SYNCHRONIZED
NOTICE  2024-10-08 16:25:51.0039 StratumServer SHARE FOUND: mainchain height 3254668, sidechain height 6, diff 112205, client 127.0.0.1:59246, user XXX, effort 178.247%
NOTICE  2024-10-08 16:28:07.2942 SideChain status
Monero node               = 127.0.0.1:18081:ZMQ:18083
Main chain height         = 3254670
Main chain hashrate       = 2.905 GH/s
Side chain ID             = mini
Side chain height         = 8872240
Side chain hashrate       = 11.491 MH/s
PPLNS window              = 2160 blocks (+61 uncles, 0 orphans)
PPLNS window duration     = 6h 16m 20s
Your wallet address       = XXX
Your shares               = 0 blocks (+0 uncles, 0 orphans)
Block reward share        = 0.000% (0.000000000000 XMR)
NOTICE  2024-10-08 16:28:07.2943 StratumServer status
Hashrate (15m est) = 8.773 KH/s
Hashrate (1h  est) = 8.773 KH/s
Hashrate (24h est) = 8.773 KH/s
Total hashes       = 2088059
Shares found       = 0
Average effort     = 92.701%
Current effort     = 1.121%
Connections        = 1 (1 incoming)
NOTICE  2024-10-08 16:28:07.2943 P2PServer status
Connections    = 12 (2 incoming)
Peer list size = 870
Uptime         = 0h 3m 58s
NOTICE  2024-10-08 16:28:07.2943 Util no background jobs running

> I placed xxx and XXX for privacy. Hope that doesn't change anything.

**Comment by Cyrix126** [comment] 2024-10-08 19:10
ok I think the issue is pretty simple. The keyword needed is present in log level 3 and above (which is the default for simple mode) but not under. You can fix your issue by setting the log level to 3 in advanced tab of p2pool while I apply a patch for the fix release.

**Comment by Cyrix126** [comment] 2024-10-08 19:25
I made a separate issue for the 0B size.

**Comment by MKRajan29** [comment] 2024-10-09 06:28
> ok I think I found the issue. The keyword needed is present in log level 3 and above (which is seems to be the default when starting p2pool without the log arg in simple mode) but not under. You can fix your issue by setting the log level to 3 in advanced tab of p2pool while I apply a patch for the fix release.

Thanks, the issue is fixed now. Hope I get a mention in the bug reporting. :)

**Comment by Cyrix126** [comment] 2024-10-09 15:10
I'll let the issue open until a release fixes it.

**Comment by Cyrix126** [comment] 2024-10-11 22:19
fixed in https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.1

**Closed by Cyrix126** 2024-10-11 22:19 UTC
Labels: bug

**Comment by MKRajan29** [comment] 2024-10-12 16:42
> fixed in https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.1

The issue seems to be persisting.

**Comment by Cyrix126** [comment] 2024-10-12 17:46
> > fixed in https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.1
> 
> The issue seems to be persisting.

I just tested and can't reproduce the bug. Are you sure to be on 1.5.1 ?

**Comment by MKRajan29** [comment] 2024-10-12 18:04
> > > fixed in https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.1
> > 
> > 
> > The issue seems to be persisting.
> 
> I just tested and can't reproduce the bug. Are you sure to be on 1.5.1 ?

Yes, updated to the latest 1.5.1

**Comment by MKRajan29** [comment] 2024-10-12 18:08
> fixed in https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.1

Does this mean the verbose level can be set to any?

**Comment by Cyrix126** [comment] 2024-10-12 18:44
> > fixed in https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.1
> 
> Does this mean the verbose level can be set to any?

Yes. It should work at any level.
Do you sync at level 3 ?
What is the output of the p2pool console at level 0 ?

I just tested on Windows 10 VM and p2pool synced.
