### ISSUE TITLE
include the WinRing0x64.sys file by default in the /xmrig folder

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#21] opened 2024-10-11 23:57 UTC
**Feature request**
include the WinRing0x64.sys file by default in the /xmrig folder

**Additional context**
https://github.com/Cyrix126/gupaxx/issues/16
if the WinRing0x64.sys file is not pressent in the xmrig folder then the hashrate will be low
![373383181-0f8f5712-593b-4a2f-903e-0c32961861ee](https://github.com/user-attachments/assets/995a66ab-af22-4084-af6e-d1f916f5b020)
to fix this you could perhaps include the WinRing0x64.sys file by default in the windows-bundle.zip

**Comment by Cyrix126** [comment] 2024-10-12 11:23
I can't reproduce the issue on a fresh Windows 10 VM. Before adding this file, I want to know in which cases it is needed.

**Comment by MKRajan29** [comment] 2024-10-20 16:46
It might be needed when the user is installing Gupaxx anew without extracting the new bundle into the old directory. maybe.

**Comment by Cyrix126** [comment] 2024-10-20 18:06
> It might be needed when the user is installing Gupaxx anew without extracting the new bundle into the old directory. maybe.

I can't see why. There is no need to extract to old directory, it will just replace older ones. And if you already have a Gupaxx version, you can update from it anyway.

**Comment by MKRajan29** [comment] 2024-10-20 19:05
But updating keeps it in the older directory itself. Just the same way the 'Rig' in Xmrig tab doesn't change with updating eventhough it should. So is the old directory's name.

**Comment by Cyrix126** [comment] 2024-11-01 21:14
closed by release [v1.5.2](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.2)

**Closed by Cyrix126** 2024-11-01 21:14 UTC
Labels: enhancement
