### ISSUE TITLE
Raffle Algorithm frequently restarts, leading to inconsistent behavior

### ISSUE THREAD

**Issue by seatsea** [Cyrix126/gupaxx#7] opened 2024-05-17 11:30 UTC
## OS & Version:
Windows 11, Gupaxx v1.1.0

## Bug
What is the bug?

The output log of the XvB algorithm shows that it frequently restarts from scratch, which then leads it to incorrectly calculate how much it should contribute to the raffle, usually leading to donating to much.

The exact behavior appears inconsistent, sometimes it fails and stops entirely, sometimes it says it can't resolve the xmrvbeast domain before eventually restarting. Or saying "Mining on p2pool for 530 then on XvB for 70 seconds" and then actively mining on XvB for more than 6 minutes. 

My current setup is as follows:

Local gupaxx rig:

- AMD 5700X, 32GB RAM
- Actively used as daily driver PC
- Mines approx 20 hours/day
- Variable hashrate 6kH/s 9.5kH/s depending on PC usage

Remote Rig with xmrig mining to the first rig
- AMD 5800X3D 32GB RAM
- Mines approx 8 hours/day
- 8kH/s consistent while mining

Current reported status:
- 15KH/s on p2pool
- 4.7kH/s last hour, 2.4kH/s 24 hours on XvB
Expected hashrate on XvB should be approx 1kH/s

My best guess is the process is regularly getting suspended somehow, maybe as it's tied to the UI thread which seems to get low priority when not the focused window. P2pool and XMRig continue to operate normally as visible in their respective logs.

**Comment by seatsea** [comment] 2024-05-17 14:09
Thanks for the detail

The behavior is rather random so I'll try capture what I can when I observe it, what I just noticed is the algorythm re-ran several times within the space of 5 minutes as seen here. 
The "Currently mining on XvB node" is also incorrect, it shouldn't be 9 minutes if the logic decided 413 seconds. 

![image](https://github.com/Cyrix126/gupaxx/assets/6282728/ec241728-52e2-4796-b11f-a397017a6038)

**Comment by Cyrix126** [comment] 2024-05-17 19:34
it seems there is another issue from your last screenshot: At timestamp 16:06:15 it says it will mine (for 10mn), but it seems that at two minutes later,  it doesn't have average HR of xmrig anymore (that will not stop the algo if it was started). It's like xmrig stopped working for a moment. Could you check the xmrig console to see if anything strange is happening ?

**Comment by seatsea** [comment] 2024-05-18 08:02
I don't see any signs of XMRig re-starting in these cases, it appears to run continuously without issue
I have changed one aspect since yesterday, I am now connecting p2pool to a full pruned node on my LAN instead of a remote one, this doesn't appear to impact the issue.

My suspicion is the UI thread hangs when running on all available CPU threads, this causes the XvB algo which appears to be tied to the UI thread, to regularly run out of resources and hang.
I've changed XMrig to run on 14 threads instead of 16. So far I haven't observed the issue again.

**Comment by Cyrix126** [comment] 2024-05-18 08:16
the algo itself is not tied to the UI thread, it runs separately.
The XvB process will however update the UI every second for the timer and every minute for the others stats.
The console is immediately updated.
I 'll look into it and try to fix this for next release.

> This morning I've changed XMrig to run on 14 threads instead of 16

Just a note: sometimes using half your threads (the number of physical cores) will give you better HR. you can test.

**Comment by seatsea** [comment] 2024-05-18 08:33
Alright thanks for looking into it! Let me know if I can provide further info. 

As for number of threads, the 5700X (and many other Zen CPUs) the best H/s benchmark is running on all threads, it's in fact what XMRig defaults to if running it standalone.

**Comment by Cyrix126** [comment] 2024-05-18 20:04
ok good news is that I can fully reproduce the bug on the VM. It easy fairly easy to reproduce: if Gupaxx is unfocused and all threads used, it will restart the algo every minutes, have the line about 10s HR of xmrig and have too long timeline for XvB node.
If focused, even with full threads, or unfocused without all threads, it will behave correctly.

**Comment by Cyrix126** [comment] 2024-05-19 14:38
Linux is not affected.

**Comment by Cyrix126** [comment] 2024-05-19 17:27
Windows will lower the priority of the thread when the window is unfocused thanks to [Dynamic Priority](https://learn.microsoft.com/en-us/windows/win32/procthread/priority-boosts).
Gupaxx needs a minimal thread priority since it is keeping track of time and making http requests.
There is a good chance also that it could fix https://github.com/Cyrix126/gupaxx/issues/6
The bug will be fixed by letting Gupaxx set his own base thread priority.

Thanks @seatsea to point me in the right direction !

**Closed** 2024-05-20 13:23 UTC
Labels: bug, good first issue
